/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#2e3132',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#ffb780',
        'on-tertiary-fixed': '#2f1400',
        'outline-variant': '#c1c8c3',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#264e40',
        'primary-container': '#1a4335',
        surface: '#f8f9fa',
        'primary-fixed-dim': '#a5d0bd',
        'on-secondary-fixed-variant': '#004c6c',
        'on-surface': '#191c1d',
        'on-secondary-fixed': '#001e2e',
        'surface-container-high': '#e7e8e9',
        'tertiary-container': '#5f2f00',
        background: '#f8f9fa',
        primary: '#002d20',
        'inverse-primary': '#a5d0bd',
        'surface-variant': '#e1e3e4',
        'surface-container-highest': '#e1e3e4',
        secondary: '#256487',
        'on-secondary': '#ffffff',
        'primary-fixed': '#c0ecd8',
        'surface-tint': '#3e6657',
        'secondary-fixed-dim': '#94cdf5',
        'on-primary-container': '#85af9d',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        outline: '#717974',
        'on-surface-variant': '#414844',
        'on-secondary-container': '#1c5d80',
        'surface-container-low': '#f3f4f5',
        error: '#ba1a1a',
        'surface-dim': '#d9dadb',
        'secondary-fixed': '#c7e7ff',
        'on-background': '#191c1d',
        'on-tertiary-container': '#e39454',
        'surface-container': '#edeeef',
        'inverse-on-surface': '#f0f1f2',
        'tertiary-fixed': '#ffdcc4',
        'on-tertiary-fixed-variant': '#6f3800',
        'surface-bright': '#f8f9fa',
        'secondary-container': '#9dd6fd',
        tertiary: '#3f1d00',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#002117',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'element-gap': '1rem',
        'safe-area-bottom': '2rem',
        'container-margin': '1.25rem',
        'island-padding': '1.5rem',
      },
      fontFamily: {
        sans: [
          'Inter',
          'Outfit',
          'System',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-xl': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
