import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0B0F19',
    overflow: 'hidden',
  },
  profileContainer: {
    flex: 1,
    backgroundColor: '#0B0F19',
    // Offset to the right of the sidebar (16px margin + ~64px sidebar + 8px gap)
    paddingLeft: 88,
    paddingTop: 8,
  },
  topBarWrapper: {
    position: 'absolute',
    // Anchored to the left side, full height
    top: Platform.OS === 'ios' ? 56 : 16,
    left: 16,
    bottom: 20,
    zIndex: 5000, // Keep above sidePanelOverlay (4000)
  },
  mapContainer: {
    ...StyleSheet.absoluteFill,
    ...Platform.select({
      web: {
        transition:
          'filter 0.5s cubic-bezier(0.16, 1, 0.3, 1), transform 0.5s cubic-bezier(0.16, 1, 0.3, 1)',
      } as any,
    }),
  },
  topOverlay: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 65 : 70,
    left: 0,
    right: 0,
    paddingTop: 10,
    zIndex: 100,
    // Sombra suave en móviles
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
      },
      android: {
        elevation: 5,
      },
      web: {
        boxShadow: '0px 4px 5px rgba(0, 0, 0, 0.3)',
      },
    }),
  },
  header: {
    alignItems: 'center',
    marginBottom: 10,
    paddingHorizontal: 20,
  },
  brandTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
    ...Platform.select({
      ios: {
        textShadowColor: 'rgba(0, 0, 0, 0.75)',
        textShadowOffset: { width: -1, height: 1 },
        textShadowRadius: 10,
      },
      android: {
        textShadowColor: 'rgba(0, 0, 0, 0.75)',
        textShadowOffset: { width: -1, height: 1 },
        textShadowRadius: 10,
      },
      web: {
        textShadow: '-1px 1px 10px rgba(0, 0, 0, 0.75)',
      },
    }),
  },
  brandSubtitle: {
    fontSize: 12,
    color: '#34D399',
    fontWeight: '600',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginTop: 4,
  },
  searchBarContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  searchInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 25,
    paddingHorizontal: 16,
    paddingVertical: 10,
    color: '#FFFFFF',
    fontSize: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  categoriesWrapper: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  categoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
    marginBottom: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  activeCategoryChip: {
    backgroundColor: '#FF6B6B',
    borderColor: '#FF6B6B',
  },
  categoryText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '500',
  },
  activeCategoryText: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  toolChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    marginBottom: 8,
    gap: 10,
  },
  activeToolChip: {
    backgroundColor: 'rgba(52, 211, 153, 0.12)',
    borderColor: 'rgba(52, 211, 153, 0.4)',
  },
  toolChipText: {
    color: '#E2E8F0',
    fontSize: 13,
    fontWeight: '600',
  },
  activeToolChipText: {
    color: '#34D399',
  },
  layersWrapper: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  layersLabel: {
    color: '#A0AEC0',
    fontSize: 11,
    fontWeight: '600',
    marginRight: 8,
    marginLeft: 4,
  },
  layerChip: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  activeLayerChip: {
    backgroundColor: 'rgba(52, 211, 153, 0.3)',
    borderColor: '#34D399',
  },
  layerChipText: {
    color: '#CBD5E0',
    fontSize: 11,
    fontWeight: '500',
  },
  activeLayerChipText: {
    color: '#34D399',
    fontWeight: '600',
  },
  premiumHandleContainer: {
    width: '100%',
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  premiumHandle: {
    width: 36,
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 2,
  },
  filterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingRight: 16,
    paddingTop: 8,
  },
  closeButtonCompact: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sidePanelOverlay: {
    ...StyleSheet.absoluteFill,
    zIndex: 4000,
  },
  sidePanelBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'transparent',
  },
  sidePanel: {
    position: 'absolute',
    zIndex: 4001,
    // ─── Ultimate Obsidian Glassmorphism ───
    backgroundColor: 'rgba(18, 22, 30, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -8 },
        shadowOpacity: 0.6,
        shadowRadius: 20,
      },
      android: {
        elevation: 24,
      },
      web: {
        backdropFilter: 'blur(30px)',
        WebkitBackdropFilter: 'blur(30px)',
        boxShadow: '0px -12px 40px rgba(0, 0, 0, 0.7)',
      },
    }),
  },
  pinchoCard: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'transparent',
    borderRadius: 18,
    padding: 2,
    borderWidth: 0,
  },
  pinchoImageColumn: {
    flexShrink: 0,
  },
  pinchoImageFrame: {
    position: 'relative',
    width: 118,
    height: 92,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#1F2937',
  },
  pinchoImage: {
    width: '100%',
    height: '100%',
  },
  pinchoImageOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(15, 23, 42, 0.25)',
  },
  pinchoStreetViewBadge: {
    position: 'absolute',
    left: 8,
    bottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(17, 24, 39, 0.92)',
  },
  pinchoStreetViewText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.1,
  },
  pinchoSourceBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.88)',
  },
  pinchoSourceBadgeText: {
    color: '#0F172A',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.6,
  },
  pinchoBody: {
    flex: 1,
    minHeight: 92,
    justifyContent: 'center',
    paddingVertical: 4,
  },
  pinchoHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  pinchoHeaderTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  pinchoTitle: {
    color: '#F9FAFB',
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 18,
  },
  pinchoSubtitle: {
    color: '#9CA3AF',
    fontSize: 11.5,
    fontWeight: '500',
    marginTop: 2,
    lineHeight: 15,
  },
  pinchoCloseButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  pinchoMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    flexWrap: 'wrap',
  },
  pinchoMetaChipPrimary: {
    paddingHorizontal: 0,
  },
  pinchoMetaChipTextPrimary: {
    color: '#34D399',
    fontSize: 12,
    fontWeight: '700',
  },
  pinchoMetaChipSecondary: {
    paddingHorizontal: 0,
  },
  pinchoMetaChipTextSecondary: {
    color: '#9CA3AF',
    fontSize: 11,
    fontWeight: '700',
  },
  pinchoActionsColumn: {
    flexShrink: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingLeft: 4,
  },
  pinchoActionButtonPrimary: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0E7C91',
    ...Platform.select({
      ios: {
        shadowColor: '#0E7C91',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.28,
        shadowRadius: 12,
      },
      android: { elevation: 5 },
      web: { boxShadow: '0px 8px 18px rgba(14, 124, 145, 0.35)' },
    }),
  },
  pinchoActionButtonSecondary: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  panelScroll: {
    flex: 1,
  },
  panelScrollContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  panelScrollContentWithBanner: {
    // El padding se maneja internamente
  },
  // Legacy liveIndicator kept for compatibility (not directly rendered)
  liveIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.2)',
  },
  // Premium compact LIVE badge, displayed inline with title
  liveIndicatorPremium: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    alignSelf: 'flex-start',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.25)',
    marginRight: 8,
    marginTop: 2,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EF4444',
    marginRight: 4,
  },
  liveText: {
    color: '#EF4444',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  bannerContainer: {
    width: '100%',
    height: 180, // Reducido para ahorrar espacio crítico
    position: 'relative',
    marginBottom: 0,
  },
  bannerImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  bannerOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0,0,0,0.18)',
  },
  // Gradiente suave de desvanecimiento en la base del banner
  bannerFadeBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 80,
    ...Platform.select({
      web: {
        background: 'linear-gradient(to bottom, transparent, rgba(18, 22, 30, 0.98))',
      },
      default: {
        backgroundColor: 'transparent',
      },
    }),
  },
  bannerHeader: {
    position: 'absolute',
    top: 14,
    left: 16,
    right: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  // ─── Premium Badge styles (badge with icon inside banner or no-banner header) ───
  cardHeaderPremium: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 10,
  },
  cardBadgePremium: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
  },
  cardBadgeTextPremium: {
    color: '#E2E8F0',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.1,
  },
  closeButtonPremium: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    ...Platform.select({
      web: {
        backdropFilter: 'blur(10px)',
        WebkitBackdropFilter: 'blur(10px)',
      },
    }),
  },
  // ─── Legacy styles preserved to avoid TS errors ───
  closeButtonLight: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  cardBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  cardBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  panelContentWrapper: {
    paddingHorizontal: 20,
  },
  panelContentWrapperWithPadding: {
    paddingHorizontal: 20,
  },
  // ─── Premium Title Row (title + live badge in same row) ───
  titleRowPremium: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 14,
    marginBottom: 5,
  },
  cardTitlePremium: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 26,
    letterSpacing: -0.3,
    flex: 1,
  },
  // ─── Compact Subheader row (organizer/source) ───
  subHeaderRowPremium: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  subHeaderTextPremium: {
    color: '#718096',
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0.1,
  },
  subHeaderOrganizerPremium: {
    fontWeight: '700',
    fontSize: 12,
  },
  cardDescPremium: {
    color: '#94A3B8',
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 14,
    fontWeight: '400',
  },
  // ─── Legacy compat ───
  cardTitle: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 6,
    lineHeight: 30,
    letterSpacing: -0.5,
  },
  cardOrganizer: {
    color: '#34D399',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 14,
    letterSpacing: 0.2,
  },
  cardDesc: {
    color: '#A0AEC0',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 24,
    fontWeight: '400',
  },
  cardDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.07)',
    marginVertical: 10,
  },
  // ─── Legacy compat ───
  actionBarContainer: {
    marginTop: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  actionInfoContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  actionInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  actionInfoText: {
    color: '#E2E8F0',
    fontSize: 13,
    fontWeight: '600',
  },
  // ─── Legacy status bar compat ───
  statusBarContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingHorizontal: 8,
    marginBottom: 24,
    marginTop: 8,
  },
  statusNodeWrapper: {
    alignItems: 'center',
    width: 85,
  },
  statusNode: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    zIndex: 2,
  },
  statusNodeActive: {
    backgroundColor: '#34D399',
    borderColor: '#34D399',
  },
  statusLabel: {
    color: '#718096',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  statusLabelActive: {
    color: '#34D399',
  },
  statusLine: {
    flex: 1,
    height: 2,
    backgroundColor: 'rgba(255,255,255,0.08)',
    marginTop: 11,
    marginHorizontal: -12,
    zIndex: 1,
  },
  statusLineActive: {
    backgroundColor: '#34D399',
  },
  // ─── Micro-Timeline Sleek LED Tracker ───
  microTimelineContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    paddingHorizontal: 2,
  },
  microNodeWrapper: {
    alignItems: 'center',
    gap: 4,
  },
  microNode: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  // Glowing active LED node
  microNodeActiveContainer: {
    width: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  microNodeActiveShadow: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderRadius: 8,
    opacity: 0.35,
    ...Platform.select({
      web: { filter: 'blur(4px)' },
    }),
  },
  microNodeActiveCore: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
    ...Platform.select({
      web: { boxShadow: '0 0 6px 2px rgba(255,255,255,0.4)' },
    }),
  },
  microLabel: {
    color: '#4A5568',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase' as const,
    textAlign: 'center' as const,
    maxWidth: 56,
  },
  microLabelCompleted: {
    color: '#718096',
  },
  microLine: {
    flex: 1,
    height: 1.5,
    backgroundColor: 'rgba(255,255,255,0.06)',
    marginBottom: 12,
    marginHorizontal: 3,
  },
  // ─── Horizontal Meta Info Grid ───
  metaInfoGrid: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    paddingVertical: 10,
    paddingHorizontal: 4,
    marginBottom: 14,
  },
  metaGridItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  metaGridDivider: {
    width: 1,
    height: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  metaGridText: {
    color: '#CBD5E0',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  addressRowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 16,
    gap: 8,
  },
  addressText: {
    color: '#E2E8F0',
    fontSize: 12.5,
    fontWeight: '500',
    lineHeight: 18,
    flex: 1,
  },
  // ─── Legacy compat ───
  actionButtonsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 16,
    flex: 2,
  },
  actionBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
    marginLeft: 8,
  },
  iconBtn: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  // ─── Premium Actions Toolbar ───
  actionButtonsContainerPremium: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  actionBtnPremium: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
    paddingHorizontal: 18,
    borderRadius: 14,
    flex: 1,
    gap: 7,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
      },
      android: { elevation: 4 },
      web: { boxShadow: '0px 4px 14px rgba(0, 0, 0, 0.35)' },
    }),
  },
  actionBtnTextPremium: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  iconBtnPremium: {
    width: 42,
    height: 42,
    borderRadius: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.07)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.09)',
    ...Platform.select({
      web: {
        backdropFilter: 'blur(8px)',
        WebkitBackdropFilter: 'blur(8px)',
      },
    }),
  },
  // ─── Check-in button states ───────────────────────────────────────────────
  checkInDoneBtn: {
    backgroundColor: 'rgba(52, 211, 153, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(52, 211, 153, 0.25)',
  },
  checkInProcessingBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  // ─── Real-time distance indicator ────────────────────────────────────────
  distanceIndicatorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 4,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  distanceDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    flexShrink: 0,
  },
  distanceText: {
    color: '#6B7280',
    fontSize: 11,
    fontWeight: '600',
    flex: 1,
  },
  checkInErrorText: {
    color: '#EF4444',
    fontSize: 10,
    fontWeight: '500',
    width: '100%',
    marginTop: 2,
  },
  unifiedControlsContainer: {
    position: 'absolute',
    bottom: 20,
    right: 12,
    zIndex: 5000, // Keep above sidePanelOverlay (4000)
    backgroundColor: 'rgba(30, 30, 30, 0.6)', // Glassmorphism premium
    borderRadius: 24, // Mismo radio de borde que los paneles principales
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 3,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: { elevation: 6 },
      web: {
        backdropFilter: 'blur(12px)', // Efecto cristal más pronunciado
        WebkitBackdropFilter: 'blur(12px)',
        boxShadow: '0px 8px 32px rgba(0, 0, 0, 0.2)',
      },
    }),
  },
  controlButton: {
    width: Platform.OS === 'web' ? 36 : 44,
    height: Platform.OS === 'web' ? 36 : 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 2,
  },
  controlButtonActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)', // Coincide con active NavLink
  },
  controlDivider: {
    width: 20,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    marginVertical: 2,
  },
  zoomSliderContainer: {
    position: 'absolute',
    right: 72,
    zIndex: 5000,
    flexDirection: 'column',
    alignItems: 'center',
  },
  zoomSliderGlass: {
    backgroundColor: 'rgba(30, 30, 30, 0.85)',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: 'center',
    gap: 12,
    height: 220,
    width: 46,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: { elevation: 6 },
      web: {
        backdropFilter: 'blur(12px)',
        WebkitBackdropFilter: 'blur(12px)',
        boxShadow: '0px 8px 32px rgba(0, 0, 0, 0.5)',
      },
    }),
  },
  zoomControlBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  zoomTrackWrapper: {
    flex: 1,
    width: 20,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    marginVertical: 4,
  },
  zoomTrackLine: {
    width: 4,
    height: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 2,
    overflow: 'hidden',
    position: 'relative',
  },
  zoomTrackFill: {
    width: '100%',
    backgroundColor: '#34D399',
    position: 'absolute',
    bottom: 0,
    left: 0,
  },
  zoomTickDot: {
    position: 'absolute',
    left: 6,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.35)',
    borderWidth: 1,
    borderColor: 'rgba(11, 15, 25, 0.8)',
  },
  zoomTickDotActive: {
    backgroundColor: '#34D399',
    width: 10,
    height: 10,
    borderRadius: 5,
    left: 5,
  },
  zoomBadge: {
    marginTop: 2,
    backgroundColor: 'rgba(52, 211, 153, 0.15)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    borderWidth: 0.5,
    borderColor: 'rgba(52, 211, 153, 0.25)',
  },
  zoomBadgeText: {
    color: '#34D399',
    fontSize: 9,
    fontWeight: '800',
  },
  filterOverlay: {
    position: 'absolute',
    bottom: 20,
    right: 72, // Separación de los controles unificados (12 + 44 + 16 de gap)
    width: 300,
    zIndex: 110,
    backgroundColor: 'rgba(30, 30, 30, 0.6)', // Glassmorphism premium unificado
    borderRadius: 24, // Mismo radio de borde
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.5,
        shadowRadius: 20,
      },
      android: { elevation: 12 },
      web: {
        backdropFilter: 'blur(12px)', // Efecto cristal más pronunciado
        WebkitBackdropFilter: 'blur(12px)',
        boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
      },
    }),
  },
  filterSectionTitle: {
    color: '#A0AEC0',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 8,
    marginTop: 4,
    paddingHorizontal: 16,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  tacticalHudContainer: {
    position: 'absolute',
    zIndex: 140,
  },
  tacticalHudGlass: {
    backgroundColor: 'rgba(34, 34, 34, 0.65)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 16,
    minWidth: 180,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
      },
      android: { elevation: 8 },
      web: {
        backdropFilter: 'blur(10px)',
        WebkitBackdropFilter: 'blur(10px)',
        boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.3)',
      },
    }),
  },
  hudHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  hudDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#10B981',
    marginRight: 8,
  },
  hudTitle: {
    color: '#34D399',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.2,
  },
  hudDataRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  hudLabel: {
    color: '#A0AEC0',
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 0.5,
    marginRight: 16,
  },
  hudValue: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  hudCreateButton: {
    backgroundColor: '#34D399',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 12,
  },
  hudCreateButtonText: {
    color: '#0B0F19',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  telemetryHudContainer: {
    position: 'absolute',
    bottom: 20,
    right: 12,
    zIndex: 110,
  },
  telemetryHudGlass: {
    backgroundColor: 'rgba(34, 34, 34, 0.65)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 16,
    width: 250,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
      },
      android: { elevation: 8 },
      web: {
        backdropFilter: 'blur(12px)',
        WebkitBackdropFilter: 'blur(12px)',
        boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.3)',
      },
    }),
  },
  telemetryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  telemetryDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#3B82F6',
    marginRight: 8,
  },
  telemetryTitle: {
    color: '#60A5FA',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 1.2,
  },
  telemetryMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  compassWrapper: {
    position: 'relative',
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  compassRing: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  compassText: {
    position: 'absolute',
    color: '#A0AEC0',
    fontSize: 10,
    fontWeight: '700',
  },
  compassTextN: {
    top: 2,
    color: '#EF4444',
  },
  compassTextS: {
    bottom: 2,
  },
  compassTextE: {
    right: 3,
  },
  compassTextO: {
    left: 3,
  },
  compassNeedle: {
    position: 'absolute',
    top: 14,
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderLeftWidth: 4,
    borderRightWidth: 4,
    borderBottomWidth: 18,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#EF4444',
  },
  compassCenterDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
    position: 'absolute',
  },
  telemetryDataColumn: {
    flex: 1,
    gap: 3,
  },
  telemetryDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 4,
  },
  telemetryDetailLabel: {
    color: '#A0AEC0',
    fontSize: 8,
    fontWeight: '700',
    width: 60,
  },
  telemetryDetailValue: {
    color: '#FFFFFF',
    fontSize: 9.5,
    fontWeight: '600',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  desktopToolsContainer: {
    marginTop: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 16,
    gap: 12,
  },
  desktopToolsTitle: {
    color: '#A0AEC0',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  desktopToolsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(167, 139, 250, 0.08)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.2)',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  desktopToolsBtnText: {
    color: '#E9D5FF',
    fontSize: 13,
    fontWeight: '600',
  },
  // ─── Premium desktop tools section ───
  desktopToolsContainerPremium: {
    marginTop: 4,
    backgroundColor: 'rgba(167, 139, 250, 0.04)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.1)',
    padding: 12,
    gap: 10,
  },
  desktopToolsTitlePremium: {
    color: '#6B7280',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase' as const,
  },
  desktopToolsBtnPremium: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(167, 139, 250, 0.07)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.15)',
    paddingVertical: 9,
    paddingHorizontal: 12,
  },
  desktopToolsBtnTextPremium: {
    color: '#C4B5FD',
    fontSize: 12,
    fontWeight: '600',
    flex: 1,
  },
  rightSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  rightSheetTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
    marginLeft: 8,
  },
  rightSheetCloseButton: {
    marginLeft: 'auto',
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rightSheetSubTitle: {
    color: '#A0AEC0',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
    marginBottom: 8,
  },
  commentBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    padding: 16,
    gap: 8,
  },
  commentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  commentAuthor: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  commentTime: {
    color: '#718096',
    fontSize: 10,
    fontWeight: '500',
  },
  commentText: {
    color: '#CBD5E0',
    fontSize: 12.5,
    lineHeight: 18,
    fontWeight: '400',
  },
  commentInputContainer: {
    marginTop: 12,
    gap: 8,
  },
  commentInputLabel: {
    color: '#A0AEC0',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  commentInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    paddingVertical: 10,
    paddingLeft: 16,
    paddingRight: 8,
  },
  commentInputPlaceholder: {
    color: '#718096',
    fontSize: 13,
  },
  sendCommentBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#A78BFA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  coordinatesBadgeFooter: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(18, 22, 30, 0.95)',
    paddingVertical: 10,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  coordinatesBadgeFooterText: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '600',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    letterSpacing: 0.5,
  },
  sheetHandle: {
    width: 36,
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 8,
    marginBottom: 4,
  },
  // --- MiniModal Styles ---
  miniModalContainer: {
    position: 'absolute',
    backgroundColor: '#111827',
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 20,
    zIndex: 1000,
  },
  miniBannerContainer: {
    height: 140,
    width: '100%',
    position: 'relative',
  },
  miniBannerImage: {
    ...StyleSheet.absoluteFill,
  },
  miniBannerOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  miniCloseButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  miniBadgeContainer: {
    position: 'absolute',
    bottom: 12,
    left: 12,
  },
  miniBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  miniBadgeText: {
    color: '#A0AEC0',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
  },
  miniContent: {
    padding: 20,
  },
  miniTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 4,
  },
  miniOrganizer: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 12,
  },
  miniDescription: {
    color: '#CBD5E0',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 16,
  },
  miniMetaGrid: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
    gap: 12,
  },
  miniMetaItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  miniMetaText: {
    color: '#A0AEC0',
    fontSize: 11,
    fontWeight: '600',
  },
  miniMetaDivider: {
    width: 1,
    height: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  miniActionRow: {
    flexDirection: 'row',
    gap: 12,
  },
  miniPrimaryBtn: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  miniPrimaryBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  miniIconBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  // ─── Sector Info Card (Parque/Reserva) — Rating, Badges, Slider, Placeholders ───
  sectorScroll: {
    flexGrow: 0,
  },
  sectorRatingBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  sectorRatingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: 'rgba(251, 191, 36, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.25)',
  },
  sectorRatingText: {
    color: '#FBBF24',
    fontSize: 12,
    fontWeight: '700',
  },
  sectorBadgePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    maxWidth: 160,
  },
  sectorBadgePillText: {
    color: '#A0AEC0',
    fontSize: 11,
    fontWeight: '600',
  },
  sectorPlaceholderSection: {
    marginTop: 14,
  },
  sectorPlaceholderTitle: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  sectorPlaceholderBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  sectorPlaceholderText: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '500',
  },
  sectorFooterRow: {
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.06)',
  },
  sectorFooterBtn: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  sectorFooterBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  sectorFooterIconBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // ─── Custom Floating Toast Notifier Styles ───
  toastContainer: {
    position: 'absolute',
    top: 50,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 99999,
    pointerEvents: 'none',
  },
  toastCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.85)', // slate-900 glass
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 9999,
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
    maxWidth: '90%',
    ...Platform.select({
      web: {
        backdropFilter: 'blur(12px)',
        WebkitBackdropFilter: 'blur(12px)',
      },
    }),
  },
  toastCard_success: {
    borderColor: 'rgba(52, 211, 153, 0.4)',
  },
  toastCard_error: {
    borderColor: 'rgba(239, 68, 68, 0.4)',
  },
  toastCard_warning: {
    borderColor: 'rgba(245, 158, 11, 0.4)',
  },
  toastCard_info: {
    borderColor: 'rgba(96, 165, 250, 0.4)',
  },
  toastMessage: {
    color: '#F8FAFC',
    fontSize: 13,
    fontWeight: '600',
  },
});
